return {
	{'nvim-tree/nvim-web-devicons'},
	{"nvim-lua/plenary.nvim"},
	require 'Treesitter',
	require 'Comments',
	require 'Nvimtree',
	require 'Telescope',
	require 'Bufferline',
	require "Alpha",
	require "Lualine",
	require "Indentline",
	require "Toggleterm",
	require "Notify",
	require "Noice",
	require "TreeSj",
	require "Lightspeed",
	require "Autopaire", -- TODO 
	require "Dressing",
	require "Cmp",
	require "lsp.Mason",
	require "lsp.MasonLspConfig",
	require "lsp.LspConfig",
	require "lsp.serverSetting.TsTools",
	require "Harpoon",
	require "dap.Dap",
	require "dap.nodeDap",
	-- require "NvimUfo", -- [commented till i fix the highlite]
}
