return {
	{'nvim-tree/nvim-web-devicons'},
	{"nvim-lua/plenary.nvim"},
	require 'Treesitter',
	require 'Comments',
	require 'Nvimtree',
	require 'Telescope',
	require 'Bufferline',
	require "Alpha",
	require "Lualine",
	require "Indentline",
	require "Toggleterm",
	require "Notify",
	require "Noice",
	require "TreeSj",
	require "Lightspeed",
	require "Autopaire", -- TODO
	require "Dressing",
	require "Cmp",
	require "lsp.Mason",
	require "lsp.MasonLspConfig",
	require "lsp.LspConfig",
	require "lsp.serverSetting.TsTools",
	require "Harpoon",
	require "dap.Dap",
	require "Neorg",
	require "NvimRest",
	require "treeNav",
	require "NeoGit",
	require "GitSign",
	require "lua_snip",
	require "friendly",
	require "autoTag",
	require "TodoCmp", -- TODO fix the vs-snippets
	-- require "NvimShip",
	-- require "dap.nodeDap",
	-- require "NvimUfo", -- [commented till i fix the highlighte]
}
